# Generated by Django 5.0.12 on 2025-04-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.TextField(default='title', verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
