# Generated by Django 5.0.12 on 2025-04-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartments',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер квартиры'),
        ),
    ]
